import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import Navbar from "../components/Navbar";

export const metadata = {
  title: "Legalyzer by Abhinav Saxena",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-[#0B1B2B] text-white font-sans">
        <AuthProvider>
          <Navbar />
          <main className="container mx-auto p-6">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
